baseURL = 'https://scylalala.github.io/'
   languageCode = 'en-us'
   title = ' ' # Leave blank for a minimal top
   theme = 'ink'

   [params]
     # Ink uses a slightly different format for social icons
     github = "https://github.com/scylalala"
